### ISSUE TITLE
[전체-금요일 QA에 대한 여러 보완]

### ISSUE THREAD

**Issue by sshrik** [woowa-techcamp-2021/store-8#170]
## 어떤 작업을 해야하나요?
- [x] ( 3h ) 크롬 개발자도구의 핸드폰 화면을 보면서 카트 / 결제 화면 반응형 구성
- [x] ( 1h ) 장바구니 내역이 수정될 때 마다 저장 ( with debounce ) 혹은 내역이 저장되지 않는다고 경고해주기
- [x] ( 0.5h ) Address 창 주소 수정 보완 ( #164 )
- [x] ( 1h ) 마일리지가 잘 호출되지 않는 버그 ( #161 )
- [x] ( 1h ) FAB 버튼 SVG 변경 및 모바일에서의 크기 조정
- [x] ( 0.5h ) 메인에 카드 Hover 시 사진 크게 해 주기, 또한 Radius 도 적당히 줘도 좋을듯.
- [x] ( 0.5h ) 메인의 카드 핸드폰에서 Hover 시 나오는게 아니라 그냥 나와있게 하기
- [x] ( 2h ) 항상 떠있는 왼쪽 추천창 ( 메인에서만 떠있지 않게 하기, 핸드폰에서도 안뜨게 하기 )
- [x] ( 1h ) 헤더의 검색창 모바일 화면에서 모습하기
- [x] ( 0.5h ) 장바구니에 동일한 항목 있으면 합쳐주기 ( #160 )

그 외의 버그 QA 하면서 고치기
